version: "3.8"

networks:
  snips_nlu_network:
    external: false
    attachable: true

volumes:
  rabbitmq:
    external: true
  nlu_data:
    driver_opts:
      type: "nfs"
      o: "addr=${IP_SERVER_NFS},nolock,rw"
      device: ":/snips-data"

services:
  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - NODENAME=${RABBITMQ_HOSTNAME}@localhost
    networks:
      - snips_nlu_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: any
  hestia:
    image: 127.0.0.1:5000/hestia
    build: 
      context: ./hestia
      args:
        - NPM_TOKEN
    ports:
      - 3000:3000
    volumes:
      - /snips-data:/home/hestia/app/snips-data
    environment:
      - RABBITMQ_URL
      - NODE_ENV
      - API_SMARTLY_ENDPOINT
    networks:
      - snips_nlu_network
    command: ["./wait-for-it.sh", "rabbitmq", "node", "index"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: any
  parsebeta:
    image: 127.0.0.1:5000/snips_parse_beta
    build: 
      context: ./snips-nlu-parse-beta
      args:
        - SSH_PRIVATE_KEY
        - SSH_PUBLIC_KEY
    ports:
      - 6500:6000
    volumes:
      - nlu_data:/snips_parse/nfs_server
    environment:
      - SNIPS_HOST=0.0.0.0
      - SNIPS_PORT=6000
      - RABBITMQ_URL
      - NSF_SERVER_PATH=/snips_parse/nfs_server
    networks:
      - snips_nlu_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type == parsebeta]
      restart_policy:
        condition: any
    command: ["gunicorn", "-b 0.0.0.0:6000", "--reload", "run_parse:smartly_parse_app"]
  trainbeta:
    image: 127.0.0.1:5000/snips_train_beta
    build: 
      context: ./snips-nlu-train-beta
      args:
        - SSH_PRIVATE_KEY
        - SSH_PUBLIC_KEY
    ports:
      - 6400:6000
    volumes:
      - nlu_data:/snips_train/nfs_server
    environment:
      - SNIPS_HOST=0.0.0.0
      - SNIPS_PORT=6000
      - RABBITMQ_URL
      - SSE_REDIS_URL=redis://redis:6379/0
      - NSF_SERVER_PATH=/snips_train/nfs_server
    networks:
      - snips_nlu_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type == train]
      restart_policy:
        condition: any
    command: ["gunicorn", "-b 0.0.0.0:6000", "--reload", "run_train:smartly_train_app"]
  parse:
    image: 127.0.0.1:5000/snips_parse
    build: 
      context: ./snips-nlu-parse
      args:
        - SSH_PRIVATE_KEY
        - SSH_PUBLIC_KEY
    ports:
      - 5500:5000
    volumes:
      - nlu_data:/snips_parse/nfs_server
    environment:
      - SNIPS_HOST=0.0.0.0
      - SNIPS_PORT=5000
      - RABBITMQ_URL
      - NSF_SERVER_PATH=/snips_parse/nfs_server
    networks:
      - snips_nlu_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type == parse]
      restart_policy:
        condition: any
    command: ["gunicorn", "-b 0.0.0.0:5000", "--reload", "run_parse:smartly_parse_app"]
  train:
    image: 127.0.0.1:5000/snips_train
    build: 
      context: ./snips-nlu-train
      args:
        - SSH_PRIVATE_KEY
        - SSH_PUBLIC_KEY
    ports:
      - 5400:5000
    volumes:
      - nlu_data:/snips_train/nfs_server
    environment:
      - SNIPS_HOST=0.0.0.0
      - SNIPS_PORT=5000
      - RABBITMQ_URL
      - SSE_REDIS_URL=redis://redis:6379/0
      - NSF_SERVER_PATH=/snips_train/nfs_server
    networks:
      - snips_nlu_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type == train]
      restart_policy:
        condition: any
    command: ["gunicorn", "-b 0.0.0.0:5000", "--reload", "run_train:smartly_train_app"]
