version: "3.3"
services:
  snipsfr:
    build: 
      context: .
    depends_on:
      - redis
    ports:
      - 5500:5000
    volumes:
      - /snips-data:/snips_smartly/nfs_server
    networks:
      - snipsntework
    environment:
      - SNIPS_HOST=0.0.0.0
      - SNIPS_PORT=5000
<<<<<<< HEAD
      - SSE_REDIS_URL=redis://redis:6379/0
=======
      - SSE_REDIS_URL = "redis://redis:6379/0"
>>>>>>> 495b38c05cb3634868cbc016a706f4c848671788
    command: ["gunicorn", "-b 0.0.0.0:5000", "--reload", "middleware:snips_app"]

  redis:
    image: "redis:alpine"
    ports:
      - 6379
    networks:
      - snipsntework

networks:
  snipsntework:
    driver: bridge
